### ISSUE TITLE
Themed vars are not propagated

### ISSUE THREAD

**Issue by olivierpascal** [facebook/stylex#162] opened 2023-12-13 10:03 UTC
**The problem**

Themes are applied only on first level.

themed(varA) -> component using varA : varA is themed

themed(varA) -> varB = varA -> component using varB : varB is not themed

**How to reproduce**

```ts
// colorScheme.stylex.ts

import * as stylex from '@stylexjs/stylex';

export const colorScheme = stylex.defineVars({
  primary: 'red',
});
```

```ts
// myComponentVars.stylex.ts

import * as stylex from '@stylexjs/stylex';
import { colorScheme } from './colorScheme.stylex';

export const myComponentVars = stylex.defineVars({
  text: colorScheme.primary, // theme not applied here
});

```

```tsx
// MyComponent.tsx

import React from 'react';
import { colorScheme } from './colorScheme.stylex';
import { myComponentVars } from './myComponentVars.stylex';

const theme = stylex.createTheme(colors, {
  primary: 'green',
});

const styles = stylex.create({
  container: {
    color: colorScheme.primary, // <- theme is applied (output green)
    color: myComponentVars.text, // <- theme is not applied (output red)
  },
});

export const MyComponent = () => <div {...stylex.props(styles.container, theme)}>TEXT</div>;
```

**Expected behavior**

Theme should be applied through `myComponentVars.text`.

The idea behind this is to allow changing all colors globally (by theming colorScheme.stylex.ts), or only component colors (by theming myComponentVars.stylex.ts).

**Comment by nmn** [comment] 2023-12-13 11:51
This is expected behaviour as it is how CSS variables work. To give you a peek behind the scenes, this the CSS that would be generated:

(I'm using readable names, but the actual output would use hashes)

```css
:root {
  /* colorScheme = defineVars */
  --primary: red;
  /* myComponentVars = defineVars */
  --text: var(--primary);
}

.theme {
  --primary: green;
}
```

Setting the theme in JS, is essentially setting a class name which sets a new value for `--primary`. However, the value for `--text` has not changed. The value for `--text` was only set globally, and at that level `--primary` is still `red`.

----

Here's the workaround:

```tsx
import React from 'react';
import { colorScheme } from './colorScheme.stylex';
import { myComponentVars } from './myComponentVars.stylex';

const theme = stylex.createTheme(colorScheme, {
  primary: 'green',
});
const componentTheme = stylex.createTheme(myComponentVars, {
  text: colorScheme.primary,
});

const styles = stylex.create({
  container: {
    color: colorScheme.primary, // <- theme is applied (output green)
    color: myComponentVars.text, // <- theme is not applied (output red)
  },
});

export const MyComponent = () => <div {...stylex.props(styles.container, theme, componentTheme)}>TEXT</div>;
```

This will re-assign the value of `--text` to the new local value of `--primary`.

**Comment by olivierpascal** [comment] 2023-12-14 19:06
@nmn  The problem of this workaround is that I cannot externally theme the component anymore, because it's already using a theme internally.

**Comment by nmn** [comment] 2023-12-14 21:53
Themes, created with CSS variables, don't need to be on the component itself. They can be set on a parent element.

**Comment by olivierpascal** [comment] 2023-12-14 22:06
Sure but it will be overridden by the local theme in the component div

**Comment by nmn** [comment] 2023-12-15 10:22
@olivierpascal Since the component is not being styled by StyleX, I think you'll need to use a different system to override its styles.

**Comment by olivierpascal** [comment] 2023-12-15 11:43
My bad, when I meant 'I cannot externally theme the component anymore', i wanted to say that if a themeB is applied to a parent element of the component, since the component is already themed by themeA, themeA will always override themeB.

**Comment by nmn** [comment] 2023-12-15 19:47
Explain your problem a bit further. With some code examples?

**Comment by nmn** [comment] 2023-12-21 07:38
Closing this issue as it seems addressed and there have been no follow-ups.

**Closed by nmn** 2023-12-21 07:38 UTC
