### ISSUE TITLE
Webpack plugin support

### ISSUE THREAD

**Issue by adrian-novacescu** [facebook/stylex#179] opened 2023-12-14 13:55 UTC
Hi,

I tried Stylex today and it works great on dev mode and storybook. My problem is that when I tried to run the production build it failed with the following error

```sh
[webpack-cli] TypeError: The 'compilation' argument must be an instance of Compilation
    at NormalModule.getCompilationHooks (/Users/adrian/_GIT/lexplore/Portal/node_modules/@stylexjs/webpack-plugin/node_modules/webpack/lib/NormalModule.js:231:10)
    at /Users/adrian/_GIT/lexplore/Portal/node_modules/@stylexjs/webpack-plugin/src/index.js:68:20
    at Hook.eval [as callAsync] (eval at create (/Users/adrian/_GIT/lexplore/Portal/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:19:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/adrian/_GIT/lexplore/Portal/node_modules/tapable/lib/Hook.js:18:14)
    at /Users/adrian/_GIT/lexplore/Portal/node_modules/webpack/lib/Compiler.js:1171:20
    at Hook.eval [as callAsync] (eval at create (/Users/adrian/_GIT/lexplore/Portal/node_modules/tapable/lib/HookCodeFactory.js:33:10), <anonymous>:22:1)
    at Hook.CALL_ASYNC_DELEGATE [as _callAsync] (/Users/adrian/_GIT/lexplore/Portal/node_modules/tapable/lib/Hook.js:18:14)
    at Compiler.compile (/Users/adrian/_GIT/lexplore/Portal/node_modules/webpack/lib/Compiler.js:1161:28)
    at /Users/adrian/_GIT/lexplore/Portal/node_modules/webpack/lib/Compiler.js:524:12
    at Compiler.readRecords (/Users/adrian/_GIT/lexplore/Portal/node_modules/webpack/lib/Compiler.js:986:5)
```

Do I need a specific webpack version? I am using "5.75.0".

Thank you for your great work and looking forward to an answer,
Adi

**Comment by adrian-novacescu** [comment] 2023-12-14 16:53
I managed to overcome that by using the latest webpack version. I also needed to update TS to version 5.X. However production build is still not working. Now I get the following error:

`
TypeError: Cannot destructure property 'code' of '(intermediate value)' as it is null.
    at StylexPlugin.transformCode (/Users/adrian/_GIT/lexplore/Portal/node_modules/@stylexjs/webpack-plugin/src/index.js:163:15)
 @ ./src/design-system/NEW/Button/Button.tsx 2:0-43 5:0-13 6:0-13 22:22-34
 @ ./src/design-system/NEW/Button/index.tsx 1:0-35 1:0-35
 @ ./src/containers/LibraryView/ActionButtons.tsx 4:0-49 43:68-77
 @ ./src/containers/LibraryView/LibraryView.tsx 32:0-65 164:40-53
 @ ./src/containers/App/PrivateRoutes/Library.tsx 3:0-61 20:40-51
 @ ./src/containers/App/PrivateRoutes/PrivateRoutes.tsx 13:0-32 45:46-53
 @ ./src/containers/App/PrivateRoutes/index.tsx 1:0-42 1:0-42
 @ ./src/containers/App/index.tsx 6:0-57 9:151-164
 @ ./src/AppProvider.tsx 12:0-35 38:7-10
 @ ./src/index.tsx
`

My component is 
`/ @ts-ignore
const styles = Stylex.create({
  primary: {
    backgroundColor: 'red',
    color: 'black',
  },
});

const Button = ({
  appearance,
  children,
  className,
  disabled,
  onClick,
  style,
}: Props) => {
  const cn = classnames(Stylex.props(styles[appearance]).className, className);
  return (
    <button disabled={disabled} onClick={onClick} type="button" className={cn}>
      {children}
    </button>
  );
};

export default Button;
`.

I had the styles built as 
`
const styles = Stylex.create({
  primary: {
    backgroundColor: {
      default: colors.primaryBackground,
      ':hover': colors.primaryBackgroundHover,
      ':active': colors.primaryBackgroundPressed,
      ':disabled': colors.colorNeutralBackgroundDisabled,
    },
    color: {
      default: colors.secondaryText,
      ':disabled': colors.colorNeutralForegroundDisabled,
    },
  },
  secondary: {
    backgroundColor: {
      default: colors.secondaryBackground,
      ':hover': colors.secondaryBackgroundHover,
      ':active': colors.secondaryBackgroundPressed,
      ':disabled': colors.colorNeutralBackgroundDisabled,
    },
    color: {
      default: colors.primaryText,
      ':disabled': colors.colorNeutralForegroundDisabled,
    },
  },
  outline: {
    borderWidth: '1px',
    borderColor: {
      default: colors.colorNeutralBorderDisabled,
      ':focus': 'black',
      ':disabled': colors.colorNeutralBorderDisabled,
    },
  },
  common: {
    boxShadow:
      'rgba(0, 0, 0, 0.12) 0px 1px 6px, rgba(0, 0, 0, 0.12) 0px 1px 4px',
    borderWidth: '2px',
    borderColor: {
      default: 'transparent',
      ':focus': 'black',
      ':disabled': colors.colorNeutralBorderDisabled,
    },
    borderRadius: bordersRadius.borderRadiusMedium,
    paddingLeft: spacing.x,
    paddingRight: spacing.x,
    paddingBottom: spacing.xs,
    paddingTop: spacing.xs,
  },
});
` but I got the following error 
`Error: /Users/adrian/_GIT/lexplore/Portal/src/design-system/NEW/Button/Button.tsx: Only static values are allowed inside of a stylex.create() call.
    at transformStyleXCreate (/Users/adrian/_GIT/lexplore/Portal/node_modules/@stylexjs/babel-plugin/lib/index.js:3922:13)
    at CallExpression (/Users/adrian/_GIT/lexplore/Portal/node_modules/@stylexjs/babel-plugin/lib/index.js:4995:15)
    at NodePath._call (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/path/context.js:82:31)
    at TraversalContext.visitQueue (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at NodePath.visit (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/path/context.js:88:52)
    at TraversalContext.visitQueue (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitMultiple (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/context.js:61:17)
    at TraversalContext.visit (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/context.js:107:19)
    at traverseNode (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at traverse (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/index.js:52:34)
    at NodePath.traverse (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/path/index.js:101:24)
    at PluginPass.enter (/Users/adrian/_GIT/lexplore/Portal/node_modules/@stylexjs/babel-plugin/lib/index.js:4988:16)
    at newFn (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/visitors.js:160:14)
    at NodePath._call (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/path/context.js:46:20)
    at NodePath.call (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/path/context.js:36:17)
    at NodePath.visit (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/path/context.js:82:31)
    at TraversalContext.visitQueue (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/context.js:86:16)
    at TraversalContext.visitSingle (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/context.js:65:19)
    at TraversalContext.visit (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/context.js:109:19)
    at traverseNode (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/traverse-node.js:22:17)
    at traverse (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/traverse/lib/index.js:52:34)
    at transformFile (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/core/lib/transformation/index.js:83:29)
    at transformFile.next (<anonymous>)
    at run (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/core/lib/transformation/index.js:24:12)
    at run.next (<anonymous>)
    at transform (/Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/core/lib/transform.js:22:41)
    at transform.next (<anonymous>)
    at step (/Users/adrian/_GIT/lexplore/Portal/node_modules/gensync/index.js:261:32)
    at /Users/adrian/_GIT/lexplore/Portal/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/adrian/_GIT/lexplore/Portal/node_modules/gensync/index.js:223:11)
    at /Users/adrian/_GIT/lexplore/Portal/node_modules/gensync/index.js:189:28
    at /Users/adrian/_GIT/lexplore/Portal/node_modules/@babel/core/lib/gensync-utils/async.js:72:7
    at /Users/adrian/_GIT/lexplore/Portal/node_modules/gensync/index.js:113:33
    at step (/Users/adrian/_GIT/lexplore/Portal/node_modules/gensync/index.js:287:14)
    at /Users/adrian/_GIT/lexplore/Portal/node_modules/gensync/index.js:273:13
    at async.call.result.err.err (/Users/adrian/_GIT/lexplore/Portal/node_modules/gensync/index.js:223:11)
`

Also when I use stylex.create typescript yelds that the function does not expect any parameters
![Screenshot 2023-12-14 at 18 51 40](https://github.com/facebook/stylex/assets/36935575/68276cf5-cd44-4c49-84ed-8a57c9054339)


Sorry for this long message.

Looking forward to your response,
Adi

**Comment by nmn** [comment] 2023-12-14 21:48
Can you share you webpack config and more details about how things are set up?

**Comment by adrian-novacescu** [comment] 2023-12-14 22:34
Sure.

I attached a zip file with webpack config, babel config, eslint config, tsconfig and package.json.
[config.zip](https://github.com/facebook/stylex/files/13678977/config.zip)

With this config I get the following error when running tsc --noEmit:
<img width="928" alt="Screenshot 2023-12-15 at 00 27 41" src="https://github.com/facebook/stylex/assets/36935575/66272f70-51f6-41a7-ad44-05923a92901d">

and I get the following errors when trying to build:
 - with imported variables defined in a .stylex.ts file
<img width="1181" alt="Screenshot 2023-12-15 at 00 29 59" src="https://github.com/facebook/stylex/assets/36935575/c599167c-1dac-4617-8760-3c8204f71608">
- with static values inside stylex.creat:
<img width="1076" alt="Screenshot 2023-12-15 at 00 32 38" src="https://github.com/facebook/stylex/assets/36935575/01d28085-64e8-4b8f-9f1c-6898b70f6434">


Please let me know if there is anything I can help with. 
Best regards,
Adi

**Comment by nmn** [comment] 2023-12-15 10:36
Thanks for this report. There seem to be two separate problems here. One with the webpack plugin and one with the typescript.

For the webpack plugin, it looks like the non-TSX parser is being used which is causing the issue. Could you try using StyleX in a single `.ts` file (no JSX) and see if you get the same errors.

-----

Regarding Typescript, what version of Typescript are you using. It looks like `tsc` is failing to parse `const` which is a relatively new TS feature.

**Comment by adrian-novacescu** [comment] 2023-12-15 10:40
In a single .ts file everything works fine. The problem appear when I add JSX. 

Regarding Typescript, I am using 4.9.4. Updating it now is not an option since TS 5.x throws lots of errors in our project and we don't have the resources of handling that now. Do you think it is also a problem of TS version for the stylex.create warning? (the one where TS says that create does not expect any parameters?)

**Comment by nmn** [comment] 2023-12-15 10:53
>  The problem appear when I add JSX.

This seems to confirm my first assumption. To verify that this is indeed the problem would you try the following:

Open the `index.js` file within `node_modules/@stylexjs/webpack-plugin` and edit it to replace line `185`, and change `: typescriptSyntaxPlugin,` to `: [typescriptSyntaxPlugin, { isTSX: true }],`

If my assumption is correct, this will solve the problem. And if so, this bug will be fixed within a few days in the next stylex release.

---

Regarding TS, I'm not sure how to help you there since our type annotations are dependent on TS 5+ in a few different ways. You could probably try to override the types for your project?

---

I don't think the `stylex.create` problem is caused by the TS error.

**Comment by adrian-novacescu** [comment] 2023-12-15 11:21
The change I've made didn't fix it. But just to be sure that I did what you expected: 

I updated typescriptSyntaxPlugin with [typescriptSyntaxPlugin, { isTSX: true }]

<img width="442" alt="Screenshot 2023-12-15 at 13 19 33" src="https://github.com/facebook/stylex/assets/36935575/977e2c58-b08c-44a9-869b-4e2341a50683">

I removed an if block from the end of the file (line 185)
<img width="337" alt="Screenshot 2023-12-15 at 13 19 45" src="https://github.com/facebook/stylex/assets/36935575/addec358-3052-4a0b-b90e-8e30b40dbff5">

The plugin looks now like this:
<img width="785" alt="Screenshot 2023-12-15 at 13 20 07" src="https://github.com/facebook/stylex/assets/36935575/d0634654-1412-420f-a772-9fea915d8502">

**Comment by nmn** [comment] 2023-12-15 11:24
Thanks for checking. Looks like it something else. I will keep testing things on my end.

**Comment by adrian-novacescu** [comment] 2023-12-15 11:46
Thanks

**Comment by jamie-shawbrook** [comment] 2023-12-19 11:18
any update on this @nmn same issue for me.

**Comment by nmn** [comment] 2023-12-19 21:10
@jamie-shawbrook I'm working on it.

**Comment by adrian-novacescu** [comment] 2023-12-24 21:38
I started a new project with latest dependencies and in this one everything works. The only remaining issue is that the filename of the css file is "styles.[contenthash].css" but this is not a show stopper at least not for me. Thanks a lot for investigating. Please let me know if should I let this issue open. I would say that it is not a bug as long as it works with latest versions of webpack and TS.

**Comment by nmn** [comment] 2024-01-02 11:26
Closing this in favour of #297

**Closed by nmn** 2024-01-02 11:26 UTC
Labels: bug, help wanted
