### ISSUE TITLE
[NextJS] global.css is required in for Stylex to function. 

### ISSUE THREAD

**Issue by madebyjonny** [facebook/stylex#268] opened 2023-12-27 23:47 UTC
**The problem**
I noticed when starting from a blank NextJS (v14) project that styleX stops working when the global.css file is removed from the root layout file. The classes generated by styleX are applied to the relevant elements but no styles are applied.

**How to reproduce**

Steps to reproduce:
1.  Create a new NextJS project.
2.  Removed the boilerplate files, keep layout & page files.  
3.  Follow the instructions from the StyleX docs for NextJS to config it.
4.  Remove the global.css import from the layout file.
5.  Should see an unstyled page and that the StyleX styles have no effect 

**Expected behavior**
I would have expected StyleX to work without the global.css file. 

**Environment (include versions). Did this work in previous versions?**
NodeJS v20.5.1 (this is the only version I have tried). 
NextJS 14.0.1 (this is the only version I have tried).

**Comment by nmn** [comment] 2023-12-28 01:26
This is a known issue and something we can't fix in the near term. I've reached out to folks from the NextJS team for help and hope to improve the situation early next year.

**Comment by madebyjonny** [comment] 2023-12-28 09:23
Thanks @nmn, could it be worth mentioning this in the docs in the meantime ?

**Comment by nmn** [comment] 2023-12-28 10:11
I'll have a fix ready very soon!

**Comment by nmn** [comment] 2023-12-29 12:49
Duplicate of #109

**Closed by nmn** 2023-12-29 12:49 UTC
Labels: enhancement, question, wontfix
