### ISSUE TITLE
borderLeft property does not work, but 'border-left' does.

### ISSUE THREAD

**Issue by ravi-upadhyay-pi** [facebook/stylex#352] opened 2024-01-14 16:01 UTC
```ts
const styles = create({
  styleName: {
    'border-left': '1px solid black', // Works.
    borderLeft: '1px solid black', // Does not work.
  }
}
```

**Comment by necolas** [comment] 2024-01-15 00:19
Hmm, neither of those should be supported. We usually require long-form properties to be used unless a short-form property supports setting a single value (e.g., `margin: 0`). Border should always require using at least `borderColor`, `borderStyle`, and `borderWidth` (when values are shared by all sides)

**Comment by ravi-upadhyay-pi** [comment] 2024-01-15 02:49
By "should not be supported", you mean setting borderLeft is a bad practice
and shouldn't be used or, that it's some limitation for the stylex css
compiler?

Also, border-left supports setting a single value like margin.

Also, this limitation/recommendation documented somewhere?

**Comment by necolas** [comment] 2024-01-15 03:04
> By "should not be supported", you mean setting borderLeft is a bad practice and shouldn't be used or, that it's some limitation for the stylex css compiler?

Both. It might be using `'border-left'` is an unintentional hack that sidesteps the `borderLeft` constraint. I recommend that you expand your code and use the 3 long-form properties I mentioned before.

**Comment by nmn** [comment] 2024-01-15 20:50
This bug was fixed in v0.4.1. Please check what version you're using.

**Comment by ravi-upadhyay-pi** [comment] 2024-01-19 16:20
Facing this issue in v0.4.1 itself.

**Comment by nmn** [comment] 2024-01-20 17:53
Could you share a reproduction of this issue? I don't see this issue anymore.

**Comment by nmn** [comment] 2024-01-26 05:57
I couldn't reproduce this issue. Please check v0.5.0. Also, try to just use `borderLeftWidth`, `borderLeftStyle` and `borderLeftColor` instead as suggested above.

**Closed by nmn** 2024-01-26 05:57 UTC
