### ISSUE TITLE
[NextJS] Only static values are allowed inside of a stylex.create() call

### ISSUE THREAD

**Issue by ebitogu** [facebook/stylex#194] opened 2023-12-15 21:46 UTC
## Problem Description:

I am encountering an issue with Next.js 14.0.4 when using Stylex. The error message I'm receiving is:

```plaintext
Error ...src/app/common/components/ui/Card/index.js: Only static values are allowed inside of a stylex.create() call.
```
## Folder Structure:
![image](https://github.com/facebook/stylex/assets/48493864/6f73726f-408d-42d5-87ec-5db87b2e4b8f)

As you can see above I have my globalToken.stylex.js file directly under the app folder. Its contents mirror those of the globalToken.stylex.ts file in the next-js-example folder.

## Code Snippets:
Here is the content of my CardTokens.stylex.js file:
```javascript

import * as stylex from '@stylexjs/stylex';

export const tokens = stylex.defineVars({
    arrowTransform: 'translateX(0)',
});

```

And the relevant section in the Card/index.js file:
```javascript
import React from 'react';
import stylex from '@stylexjs/stylex';
import { globalTokens as $, spacing, text } from 'app/globalTokens.stylex';
import { colors } from '@stylexjs/open-props/lib/colors.stylex';
import { tokens } from './CardTokens.stylex';

const MOBILE = '@media (max-width: 700px)';
const REDUCE_MOTION = '@media (prefers-reduced-motion: reduce)';

const bgDefault = `rgba(${$.cardR}, ${$.cardG}, ${$.cardB}, 0)`;

const styles = stylex.create({
    link: {
        display: {
            default: 'flex',
            [MOBILE]: 'block',
        },
        alignItems: 'center',
        justifyContent: 'flex-start',
        flexDirection: 'column',
        borderRadius: spacing.xs,
        backgroundColor: {
            // default: bgDefault,
            // ':hover': `rgba(${$.cardR}, ${$.cardG}, ${$.cardB}, 0.1)`,
        },

```

## Issue:
The error disappears when I comment out the line:

```javascript
 import { globalTokens as $, spacing, text } from 'app/globalTokens.stylex';
```

Is the issue related to globalToken not being a relative import? This seems unlikely as all values used are static, and nothing is dynamic.

I would greatly appreciate any insights or assistance in resolving this issue. Thank you for your time and help.

**Comment by nedjulius** [comment] 2023-12-16 00:54
Hey, I think this is a duplicate of issue #40

https://github.com/facebook/stylex/issues/40

**Comment by nmn** [comment] 2023-12-16 05:22
```ts
import { globalTokens as $, spacing, text } from 'app/globalTokens.stylex';
```

This is not a relative import and so it won't work at the moment. Use `../`, i.e. a relative path to make it work. If that fixes the issue, it's a duplicate of #40 as mentioned by @nedjulius.

BTW, will be fixing this issue soon.

**Comment by ebitogu** [comment] 2023-12-16 06:23
Wow! @nmn You were right, the following was what worked for me:

```javascript
import { globalTokens as $, spacing, text } from '../../../../globalTokens.stylex';
```

Good to know this and thanks for the assurance that it will be fixed soon. Thank you for your time

**Comment by nmn** [comment] 2023-12-16 22:45
Closing this as it's a duplicate of #40

**Closed by nmn** 2023-12-16 22:45 UTC

**Comment by AbhiPartha** [comment] 2024-02-06 11:22
I get this issue even with relative imports. For example you can use this repo to reproduce it. https://github.com/millnut/storybook_foundations/tree/feature/stylex-support

Any idea why this could be happening ? 
Node version: v18.18.2
