### ISSUE TITLE
`StyleXStyles` type error for styles that use variables

### ISSUE THREAD

**Issue by QingqiShi** [facebook/stylex#356] opened 2024-01-17 00:45 UTC
**The problem**

While implementing styles in components using StyleXStyles, as outlined in [the documentation](https://stylexjs.com/docs/learn/styling-ui/using-styles/#accepting-styles-in-components), I'm encountering a TypeScript error with styles that include variables. The error is as follows:

```
Type 'Readonly<{ readonly position: StyleXClassNameFor<"position", "absolute">; readonly top: StyleXClassNameFor<"top", 0>; readonly zIndex: StyleXClassNameFor<"zIndex", 90>; readonly right: StyleXClassNameFor<...>; readonly opacity: StyleXClassNameFor<...>; readonly pointerEvents: StyleXClassNameFor<...>; }>' is not assignable to type 'StyleXStyles | undefined'.
  Type 'Readonly<{ readonly position: StyleXClassNameFor<"position", "absolute">; readonly top: StyleXClassNameFor<"top", 0>; readonly zIndex: StyleXClassNameFor<"zIndex", 90>; readonly right: StyleXClassNameFor<...>; readonly opacity: StyleXClassNameFor<...>; readonly pointerEvents: StyleXClassNameFor<...>; }>' is not assignable to type 'Readonly<Readonly<{ readonly theme?: StyleXClassNameFor<"theme", Readonly<string | null | undefined>> | undefined; readonly MozOsxFontSmoothing?: StyleXClassNameFor<"MozOsxFontSmoothing", Readonly<...>> | undefined; ... 534 more ...; readonly '::-webkit-search-results-decoration'?: StyleXClassNameFor<...> | undefine...'.
    Types of property 'opacity' are incompatible.
      Type 'StyleXClassNameFor<"opacity", string>' is not assignable to type 'StyleXClassNameFor<"opacity", Readonly<number | all | undefined>> | undefined'.
        Type 'StyleXClassNameFor<"opacity", string>' is not assignable to type 'StyleXClassNameFor<"opacity", Readonly<number | all | undefined>>'.ts(2322)
button.tsx(8, 3): The expected type comes from property 'style' which is declared here on type 'IntrinsicAttributes & ButtonStyles'
(property) ButtonStyles.style?: x.StyleXStyles | undefined
```

This issue arises when attempting to pass styles, which include CSS variables, to a component.

**How to reproduce**

Steps to reproduce:

1. Define a component that accepts a style prop, as per the documentation:

```tsx
interface ButtonProps extends Omit<ComponentProps<"button">, "className" | "style"> {
  style?: StyleXStyles;
}

function Button({ style, ...props }: ButtonProps) {
  return <button {...props} {stylex.props(styles.base, style)} />;
}
```

2. In a separate component, define a style that typically uses a numeric value but uses a variable in this case:

```tsx
// tokens.stylex.ts
const tokens = stylex.defineVars({
  opacity: '0',
});

// my-component.tsx
const styles = stylex.create({
  devicesButton: {
    opacity: tokens.opacity,
  },
};

function MyComponent() {
  return <Button style={styles.devicesButton} />;
}
```

4. Notice the TypeScript error on the style prop, which indicates a mismatch in the expected type for the 'opacity' property.

**Expected behavior**

The style prop should be compatible with the properties accepted by stylex.props. I propose that the type definition might be more accurately defined as:

```
style?: StyleXArray<
      | (null | undefined | CompiledStyles)
      | boolean
      | Readonly<[CompiledStyles, InlineStyles]>
    >
```

If this is the correct definition, it would be beneficial to have the relevant types (`CompiledStyles`, `InlineStyles`, and `StyleXArray`) made available for import (and the documentation updated). Alternatively, `StyleXStyles` could be updated to reflect this structure.

Looking forward to your suggestions or updates regarding this matter. Thank you for your assistance.

**Comment by nmn** [comment] 2024-01-17 18:45
Thanks for the bug report. I will update `opacity` to accept strings which should fix the issue. In the mean time, you should be able to workaround the problem by using `StyleXStyle<{opacity: number | string, ....}>`.

**Comment by yousoumar** [comment] 2024-01-18 08:44
I would wanna work on this if possible @nmn. I was looking for it in the codebase. Is it line 479 in `packages/stylex/src/StyleXCSSTypes.js`?

**Comment by QingqiShi** [comment] 2024-01-20 03:25
@nmn Looking at the solution from @yousoumar , I'm wondering if we need to make all property be able to receive a string? Any property can be assigned a css custom property which would be a string, right?

**Comment by nmn** [comment] 2024-01-20 17:59
@QingqiShi You're correct. Everything should accept strings now.

**Comment by yousoumar** [comment] 2024-01-20 18:37
@nmn should I complete my PR?

**Comment by nmn** [comment] 2024-01-20 23:39
@yousoumar If you wish to. I will accept a PR that only add string for some of them. And don't add `string` to properties that only accept a union of static string values anyway.

**Comment by yousoumar** [comment] 2024-01-23 07:46
Hi @nmn ! How about we merge the current PR, close this ticket, and I come up with a follow-up PR later for the possible remaining properties (as at first glance, a lot of them already supports `string` values)?

**Closed** 2024-01-24 08:09 UTC
Labels: bug

**Comment by QingqiShi** [comment] 2024-01-27 13:18
Thanks guys!

**Comment by nmn** [comment] 2024-01-28 02:52
@QingqiShi I saw your question about why `----foo` and not `--foo`. Let me try to explain.

The simplest reason is specificity. Say `--foo` is used in a `div`, but also in the `div::after`. Normally, `div::after` would have higher specificity that `div`. But inline styles have higher specificity.

So if we set `--foo` directly in an inline style it might override the value of `--foo` in a more specific case like `::after` or `@supports` query etc. So instead, we set `----foo` in the inline style, and set `--foo: var(----foo)` as regular CSS working around that problem. If you try to set `--foo` dynamically in a non-default case like `::after`, we generate a different variable name and not `----foo` so that there are no conflicts.

I know this is a bit hard to wrap your head around, but hopefully that helps?

**Comment by QingqiShi** [comment] 2024-01-28 13:02
_For others, the context for above is https://github.com/facebook/stylex/pull/376_

Thank you @nmn for taking the time to explain. However I'm still having a hard time understanding why defining `--foo` as an inline style would cause specificity problem.

Say I have an element with the inline style

```
<div class="test" style="--foo: 123px;">test</div>
```

and I have

```
.test::after {
  --foo: 456px;
}
```

`--foo` should be set as `456px` in the `::after` as expected? And for the `div` itself we'd expect the inline style to be used anyways.

I created a simple example here https://codesandbox.io/p/sandbox/test-specificity-forked-hxvcwf?file=%2Fsrc%2FApp.js to show how defining `--foo` and `----foo` yielded the same result. If you could tweak it to show an example where it doesn't give the same result that would greatly help me understand.

Again thank you for your time!

**Comment by nmn** [comment] 2024-01-28 13:18
@QingqiShi It was my mistake to use the `::after` example. You're right that your example would work correctly. But consider if it was `:hover` instead. Then the inline style would take precedence over the CSS for `:hover`.

Now, we don't officially allow `:hover` and base styles to generally be mixed, so there me be some opportunity for future optimisation here. (Not yet, because in some scenarios using `:hover` without default styles works today). But also...

There is also another issue, which is the issue of what variables show up in the CSS file which variables don't. As long as every variable that is *ever* overridden shows up in the static CSS file (and not just inline styles), then we can detect all variables that are *never* overridden and use CSS post processing to simply inline their values and remove those variables from the CSS entirely. (We would also remove unused variables this way). If we rely on inline styles to reassign variables, we may accidentally inline a variable which shouldn't be.

Any variables that are set as inline styles are never *set* in the static CSS file, only read, and so the CSS post-processing will never be able to accidentally inline them.

...

As I said, the issue is full of minutiae...

-----


Also, sorry I just realised that this information was dumped in the wrong issue. Sorry for the noise everyone else!

**Comment by QingqiShi** [comment] 2024-01-28 16:52
Ah yes. You are absolutely right, I updated my codesandbox to use `:hover` instead and can now see the difference. Thank you for explaining!

**Comment by YasinAkimura** [comment] 2024-03-09 17:50
Just found out that zIndex only allows numbers using !important suffix results in a type error. 
I'm not sure if StyleX makes it automatically compatible but I was trying to use position with StyleSheet.firstThatWorks("sticky", '-webkit-sticky'), but it won't allow -webkit-sticky.

Is there a reason behind or is it missing?
Version: 0.5.1
