### ISSUE TITLE
Can't get the project to run locally on Windows

### ISSUE THREAD

**Issue by Madses** [facebook/stylex#78] opened 2023-12-07 02:11 UTC
Node version: v18.18.1
NPM: 9.8.1

Steps followed: 
- Forked the repository
- Ran npm install in the root directory
- Ran npm start -w docs 

![image](https://github.com/facebook/stylex/assets/14233873/fb450eae-98ec-42f8-88f1-083789a4ec3f)

```Error: Cannot find package 'C:\Users\Kevin\Documents\stylex\node_modules\@stylexjs\babel-plugin\' imported from C:\Users\Kevin\Documents\stylex\apps\docs\babel-virtual-resolve-base.js```

Am I missing a step? It seems every command I try (build) results in some sort of error. 

https://github.com/facebook/stylex/blob/main/.github/CONTRIBUTING.md

**Comment by nmn** [comment] 2023-12-07 02:16
Did you already run `npm i` at root of the repo?

Otherwise, this feels like a Windows incompatibility. I will find my PC and try to reproduce this issue.

**Comment by Madses** [comment] 2023-12-07 02:23
Yeah first thing I di. I will also try to get it working on my macbook. Will get back to you with my results as soon I get the chance

**Comment by nedjulius** [comment] 2023-12-07 02:44
I had the same issue on `macOS Ventura 13.3.1`. Was able to start the development server after I manually built `@stylexjs/babel-plugin`, `@stylexjs/eslint-plugin`, `@stylexjs/shared` and `@stylexjs/stylexjs`.

**Comment by Madses** [comment] 2023-12-07 02:44
UPDATE: yeah, I seem to be getting similar issues on Mac OS.

**Comment by Madses** [comment] 2023-12-07 02:47
@nedjulius 

Maybe a silly question, but how exactly do I manually build these?

**Comment by nedjulius** [comment] 2023-12-07 02:49
> @nedjulius
> 
> Maybe a silly question, but how exactly do I manually build these?

According to the root `README`, you can either build all packages at once or specify the package name with `-w` flag. I tried building them all, but it failed (I assume because some of the packages don't have a specified build command) so I just manually built the dependencies in the `docs` app. I did that by running the `npm run build -w <package-name>` from the root of the monorepo, where `<package-name>` stands for those packages that I listed.

**Comment by nonzzz** [comment] 2023-12-07 07:07
Did you build the babel plugin before running the doc?

**Comment by ncharanaraj** [comment] 2023-12-07 15:16
Hi everyone, I tried the above commands but I'm getting errors. @kevintyj  Can you please help?
![Screenshot (104)](https://github.com/facebook/stylex/assets/43924299/bed62b6b-5fbf-43e5-80e1-6e5e366b1c4c)

**Comment by kevintyj** [comment] 2023-12-07 15:18
> Hi everyone, I tried the above commands but I'm getting errors. @kevintyj Can you please help? 

I don't see a node_modules folder, did you run `npm install`?

**Comment by ncharanaraj** [comment] 2023-12-07 15:22
I haven't run that command. According to the doc that commands on the top so i thaught we need run that first. I will do npm install now.

**Comment by Madses** [comment] 2023-12-07 16:28
I'm still having the same issues after running ``` npm run build -w @stylexjs/stylex -w @stylexjs/shared -w @stylexjs/eslint-plugin -w @stylexjs/babel-plugin```

as suggested by @kevintyj

**Comment by vaishnavrajendran** [comment] 2023-12-08 14:23
![image](https://github.com/facebook/stylex/assets/113851217/dca85ea5-c2a5-4ebc-905b-6d57bf69d0cd)
Cannot able to do npm install on windows machine. My node version is 18 and npm version is 9.8

**Comment by weti09** [comment] 2023-12-08 20:15
Using the latest version of Node.js won't fix the issue.

**Comment by nmn** [comment] 2023-12-09 08:52
We're updating the instructions, but when you first clone the repo the very next steps are:

```sh
$ npm install
$ npm run build
```

You can't build and run the docs website without first running `npm run build` at the root directory. `npm run build` will build *everything* and then you can work on specific parts as needed.

**Comment by weti09** [comment] 2023-12-09 10:01
@nmn Yes, using a WSL works. But it would be great to find the issue so we don't have to start a WSL every time.

**Comment by nmn** [comment] 2023-12-09 10:40
@weti09 Yes, working on getting this problem solved, but it's good to know that there is a workaround available in the meantime.

**Comment by nmn** [comment] 2023-12-09 11:59
Quick Update: I have reproduced the problem and identified the various causes for breakages.

I'm going to describe a workaround here, but I will work to fix at least some of these problems in the repo itself, so you need to handle fewer workarounds manually.



## Step 0: Git clone & delete the `postinstall` script from the root package.json

We need to make some tweaks to the build scripts so we need to ensure that we can install node_modules without triggering a build.

## Step 1: Disable every `prebuild` script in `packages`.

There is a `prebuild` script in most of the packages. Rename it to something like `pre:build`, so it doesn't run automatically before the `build` script. All the packages except bundler and framework plugins have this script.

## Step 2: Install `cross-env` at root directory

Just run `npm i -D cross-env` at root of the project

## Step 3: Use windows friendly commands withing `apps/docs`

In the `apps/docs/package.json` file, replace `rm -rf` with `rimraf` and replace `NODE_ENV=...` with `cross-env NODE_ENV=...`

---

Now, hopefully, running `npm run build` from the root of the project should run successfully.

# Don't include any of the `package.json` file changes in your commits or PRs.

Please don't include any changes to the `package.json` (or `package-lock`) files in your commits as these are all workarounds and not meant to be merged into the repo haphazardly.

# Ramifications 

The primary loss of functionality will be the lack of the generation of type definition files for Flow and Typescript. In practice, Flow has been configured to read the types from
the source files directly so there is no need to generate Flow type definition files to get
type-checking while contributing code. `gen-types` is only really necessary for publishing
to NPM.

The one piece of lost functionality is typescript types that are made available to the NextJS example app. This is unavoidable until we find a solution to making `gen-types` work on Windows.

# Next steps

I will add fixes with `rimraf` and `cross-env` by tomorrow.

I will think about the best approach for dealing with `gen-types`.

**Comment by weti09** [comment] 2023-12-09 12:11
Maybe add a link to the workaround in the Contribution Guide (if not already done)? This would help avoid more questions about this until more fixes are available.

**Comment by nmn** [comment] 2023-12-09 12:12
I hope to fix everything such that no workarounds are needed.

**Closed** 2023-12-09 13:04 UTC
Labels: bug, help wanted
