### ISSUE TITLE
Storybook and dark mode

### ISSUE THREAD

**Issue by millnut** [facebook/stylex#221] opened 2023-12-20 16:08 UTC
**The problem**
I have StyleX working in our Storybook 7 implementation with webpack, however as soon as I add dark mode handling in the global tokens StyleX the styling no longer works.

globalTokens.stylex.ts

```tsx
import stylex from '@stylexjs/stylex';

const DARK_MODE = '@media (prefers-color-scheme: dark)';

export const globalTokens = stylex.defineVars({
  primaryText: {
    default: 'red',
    [DARK_MODE]: 'white'
  },
  primaryBackground: {
    default: 'white',
    [DARK_MODE]: 'black'
  }
});
```

Button.stylex.ts

```tsx
import * as stylex from '@stylexjs/stylex';
import { globalTokens as $ } from '../../stylex/globalTokens.stylex';

export const styles = stylex.create({
  base: {
    padding: '1px 20px',
    borderWidth: '1px',
    borderStyle: 'solid',
    borderColor: 'black',
    borderRadius: 5,
    textDecoration: 'none'
    color: {
      default: $.primaryText,
      ':hover': 'white'
    },
    backgroundColor: {
      default: $.primaryBackground,
      ':hover': 'red'
    }
  },
});
```

If further info is required I can link to the branch in our public repo

**Comment by nmn** [comment] 2023-12-20 19:59
Yes. Please provide more information.

**Comment by millnut** [comment] 2023-12-20 20:21
No problem @nmn here is the branch I have started testing StyleX with (https://github.com/millnut/storybook_foundations/tree/feature/stylex-support) you can get this up and running with the following;

```
npm install
npm run storybook
```

The only component I have converted to StyleX is `Button` it works as is without the DarkMode switching but if you make the necessary changes in `globalTokens.stylex.ts` and uncomment the code it will break styling.

**Comment by shawngustaw** [comment] 2023-12-20 20:57
I'm also experiencing the same issue. I forked your stylex/app router demo again and integrated storybook into it (`npx storybook@latest init`) and created a Stackblitz here: https://stackblitz.com/~/github.com/shawngustaw/nextjs-app-dir-stylex

You can run it by letting `npm i` finish and then run `npm run storybook`.

**Comment by nmn** [comment] 2023-12-21 02:42
Thanks for the reproduction projects. I'll look into it.

**Comment by o-alexandrov** [comment] 2023-12-21 07:12
Isn’t it a duplicate of #112

**Comment by nmn** [comment] 2023-12-21 09:55
> imho, stylex is harmful to use until media queries can be shared ... leading to different use of media queries

@o-alexandrov I wouldn't go this far. There is a common wisdom to use extremely strict breakpoints, but for fluid responsive design it makes a lot of sense to use breakpoints to fit the needs of particular components. A feed-based interface may have a lot of empty horizontal space around the content area, but a busy header. Here it would make sense to use different breakpoints for the header vs the content area.

It's really a question of the design.

**Comment by o-alexandrov** [comment] 2023-12-21 12:49
@nmn I'm surprised about your relaxed view (closing #112 w/o built-in solution) on strictness (reusability) of media queries. This should be a problem of big teams (ex. Facebook) where enforcement of rules leads to faster work and avoidance of errors (queries mismatch).

**Comment by necolas** [comment] 2023-12-21 18:55
We used types for that. I expect continued use of MQs in components to be short lived as Container Queries are the right API for responsive components.

**Comment by nmn** [comment] 2023-12-21 20:44
@o-alexandrov We don't consider "queries mismatch" an error at all, but I understand if the strictness is important for certain designs.

**Comment by olivierpascal** [comment] 2023-12-26 06:14
Maybe this is related to https://github.com/facebook/stylex/issues/122#issuecomment-1867259172

Did not have time to try to reproduce it in production (production pipeline not ready yet).

**Comment by millnut** [comment] 2023-12-28 11:45
I think this is caused by https://github.com/facebook/stylex/issues/235 and is fixed, just waiting for a new release to confirm

**Comment by millnut** [comment] 2023-12-29 14:26
After upgrading to `v0.4.1` this now throws the following error;

```
Only static values are allowed inside of a stylex.create() call.
```

**Comment by shawngustaw** [comment] 2023-12-29 20:50
Any chance anyone figured out how to make this work with the `@storybook/nextjs` plugin? Not sure if I should be trying to use the webpack plugin or the nextjs plugin. Here's the webpack config that needs to be integrated with one of the stylex plugins: https://github.com/storybookjs/storybook/blob/next/code/frameworks/nextjs/src/config/webpack.ts

**Comment by nmn** [comment] 2023-12-30 01:26
@millnut This feels like a bug in the code itself. Is the link you shared above still current?

**Comment by millnut** [comment] 2023-12-30 10:17
Yep I've pushed the 0.4.1 upgrade to this branch and it's only the component `Button` that we are testing with StyleX https://github.com/millnut/storybook_foundations/tree/feature/stylex-support/src/components/Button, and the globalTokens are here https://github.com/millnut/storybook_foundations/blob/feature/stylex-support/src/stylex/globalTokens.stylex.ts.

When starting with `npm run storybook` we get the error `Only static values are allowed inside of a stylex.create() call.` which points to the globalTokens StyleX file.

Looking at our code, the NextJS example, and the StyleX documentation this case should work.

**Comment by nmn** [comment] 2024-01-02 13:50
I did some digging and looks like you need custom configuration for Storybook specifically.

https://storybook.js.org/docs/api/main-config-babel#babelconfig

I recommend configuring the Babel config for Storybook with the one used in the NextJS example and to set `dev` and `runtimeInjection` to `true`.

Since storybook is a developer's tool, it should be OK to have runtime style injection.

----

If this doesn't work, you can use `@stylexjs/dev-runtime` to run all of StyleX at runtime. This will have even worse performance, but it works without any build setup.

**Closed by nmn** 2024-01-02 13:50 UTC
Labels: help wanted, question

**Comment by benekuehn** [comment] 2024-01-02 15:36
I use the webpack plugin in `.storybook/main.ts`. With that it works fine!

```typescript
  webpackFinal: async (config) => {
      config.module = config.module || {};
      config.module.rules = config.module.rules || [];

      config.plugins = config.plugins || [];
      config.plugins.push(
          new StylexPlugin({
              // get webpack mode and set value for dev
              dev: config.mode === 'development',
              // Required for CSS variable support
              appendTo: 'head',
              unstable_moduleResolution: {
                  // The module system to be used.
                  // Use this value when using `ESModules`.
                  type: 'commonJS',
                  // The absolute path to the root directory of your project.
                  rootDir: __dirname,
              },
          }),
      );

      return config;
  },
```

**Comment by millnut** [comment] 2024-01-02 15:45
Thanks @nmn and @benekuehn I was able to pin this down to `framework.options.builder.useSWC` setting to `false` it works but `true` it causes the error mentioned previously.

```ts
framework: {
    name: '@storybook/react-webpack5',
    options: {
      builder: {
        useSWC: false
      }
    }
  },
```
