### ISSUE TITLE
CSS Properties don't get written (esbuild)

### ISSUE THREAD

**Issue by jonnitto** [facebook/stylex#492] opened 2024-03-14 13:09 UTC
### Describe the issue

I use `esbuild` togehter with `stylex.defineVars`. Sometimes the custom properties in `:root` get's written, but most of the time, the will not appear in the `css` file. Even when I run it with the `build` command, without a watcher.

I've got no clue, why this does this happen. No error in the cli, nothing.

### Expected behavior

The custom properties gets written every time

### Steps to reproduce

1. Start using `stylex.defineVars` in a esbuild project. After some time, event without a change on the styles, to custom properties doesn't appear anymore.

### Additional comments

I don't know if this has something to do with #363

**Comment by nedjulius** [comment] 2024-03-15 06:06
This seems to be a duplicate of #454. It's already fixed, but the fix is not published yet. In the meantime, you can try manually setting `treeshakeCompensation` option to `true` in the StyleX plugin.

**Closed** 2024-03-17 08:11 UTC
Labels: bug
